services:
  - type: web
    name: pdf-slide-extractor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: false
    services:
  - type: web
    name: pdf-slide-extractor
    env: python
    entrypoint: gunicorn main:app --bind 0.0.0.0:$PORT --timeout 300
